version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./temp/localstack:/var/lib/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  localstack-init:
    image: amazon/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh
    command: >
      -c "
      echo 'Creating S3 bucket...' &&
      aws --endpoint-url=http://localstack:4566 s3 mb s3://netsy-dev &&
      echo 'Bucket created successfully!'
      "
    restart: "no"
    depends_on:
      localstack:
        condition: service_healthy
